# Generated by Django 2.2.24 on 2021-09-03 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='公告名称')),
                ('notice_content', models.TextField(verbose_name='公告内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_newest', models.BooleanField(default=False, verbose_name='是否最新发布')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否已经发布')),
            ],
            options={
                'db_table': 'notice_info',
            },
        ),
    ]
