# Generated by Django 2.2.5 on 2019-10-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, default='http://www.baimaohui.net/home/image/icon-anquan-logo.png', max_length=100, null=True, verbose_name='头像'),
        ),
    ]
