# Generated by Django 2.2.10 on 2020-05-08 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=256, unique=True, verbose_name='Docker镜像名称')),
                ('image_vul_name', models.CharField(max_length=256, verbose_name='漏洞名称')),
                ('image_port', models.CharField(max_length=256, verbose_name='暴露端口')),
                ('image_desc', models.TextField(null=True, verbose_name='镜像描述')),
                ('rank', models.FloatField(verbose_name='Rank')),
                ('is_ok', models.BooleanField(default=True, verbose_name='镜像是否可用')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Docker创建时间，默认为当前时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Docker更新时间，默认为当前时间')),
            ],
            options={
                'db_table': 'image_info',
            },
        ),
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=255, unique=True, verbose_name='配置名称对应key')),
                ('config_value', models.TextField(default='', null=True, verbose_name='对应值')),
            ],
            options={
                'db_table': 'sys_config',
            },
        ),
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='使用用户ID')),
                ('operation_type', models.CharField(max_length=255, verbose_name='操作类型')),
                ('operation_name', models.CharField(max_length=255, verbose_name='操作名称')),
                ('operation_value', models.CharField(max_length=255, verbose_name='操作内容')),
                ('operation_args', models.TextField(default='', null=True, verbose_name='参数')),
                ('ip', models.CharField(max_length=255, verbose_name='IP地址')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'sys_log',
            },
        ),
        migrations.CreateModel(
            name='ContainerVul',
            fields=[
                ('container_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='漏洞容器创建ID')),
                ('docker_container_id', models.CharField(max_length=255, verbose_name='Docker容器运行进ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('vul_host', models.CharField(max_length=255, verbose_name='容器漏洞URL')),
                ('container_status', models.CharField(max_length=255, verbose_name='容器当前状态')),
                ('container_port', models.CharField(max_length=255, verbose_name='容器端口')),
                ('vul_port', models.TextField(default='', verbose_name='容器对应端口')),
                ('container_flag', models.CharField(max_length=255, verbose_name='flag')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='容器创建时间，默认为当前时间')),
                ('is_check', models.BooleanField(default=False, verbose_name='Flag是否通过')),
                ('is_check_date', models.DateTimeField(null=True, verbose_name='Flag提交时间')),
                ('time_model_id', models.CharField(max_length=255, verbose_name='时间模式 ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockerapi.ImageInfo', verbose_name='Docker ID')),
            ],
            options={
                'db_table': 'container_vul',
            },
        ),
    ]
