# Generated by Django 2.2.5 on 2019-10-29 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0002_auto_20191029_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containervul',
            name='container_id',
            field=models.UUIDField(default=uuid.UUID('da7fb088-fa18-11e9-ba43-8c8590a149dc'), primary_key=True, serialize=False, verbose_name='漏洞容器创建ID'),
        ),
        migrations.AlterField(
            model_name='containervul',
            name='time_model_id',
            field=models.UUIDField(default='', verbose_name='时间模式 ID'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='image_id',
            field=models.UUIDField(default=uuid.UUID('da7f9954-fa18-11e9-ba43-8c8590a149dc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.UUIDField(default=uuid.UUID('da7fc8de-fa18-11e9-ba43-8c8590a149dc'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
