# Generated by Django 2.2.5 on 2019-10-29 07:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0003_auto_20191029_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containervul',
            name='container_id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='漏洞容器创建ID'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='image_id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
