# Generated by Django 2.2.5 on 2019-10-29 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0004_auto_20191029_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containervul',
            name='container_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='漏洞容器创建ID'),
        ),
        migrations.AlterField(
            model_name='containervul',
            name='time_model_id',
            field=models.CharField(default='', max_length=255, verbose_name='时间模式 ID'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='image_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='1e5a9d0a-9bc7-4493-9ffb-c91f12bdc9a7', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
