# Generated by Django 2.2.5 on 2019-11-28 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0005_auto_20191029_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinationImage',
            fields=[
                ('combination_image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='组合镜像ID')),
                ('combination_image_name', models.CharField(max_length=255, verbose_name='组合镜像名称')),
                ('create_user', models.IntegerField(verbose_name='创建用户ID')),
                ('net_work_id', models.CharField(max_length=255, verbose_name='网卡ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'combination_image',
            },
        ),
        migrations.CreateModel(
            name='CombinationImageInfo',
            fields=[
                ('combination_image_info_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_image_id', models.UUIDField(editable=False, verbose_name='组合镜像ID')),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='镜像ID')),
            ],
            options={
                'db_table': 'combination_image_info',
            },
        ),
        migrations.CreateModel(
            name='CombinationInfo',
            fields=[
                ('combination_info_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_image_id', models.UUIDField(editable=False, verbose_name='组合镜像ID')),
                ('user_id', models.IntegerField(verbose_name='创建用户')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'combination_info',
            },
        ),
        migrations.CreateModel(
            name='NetWorkInfo',
            fields=[
                ('net_work_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='网卡UUID')),
                ('net_work_name', models.CharField(max_length=255, verbose_name='网卡名称')),
                ('net_work_subnet', models.CharField(max_length=255, verbose_name='子网')),
                ('net_work_gateway', models.CharField(max_length=255, verbose_name='网关')),
                ('net_work_scope', models.CharField(default='local', max_length=255, verbose_name='空间')),
                ('net_work_driver', models.CharField(default='bridge', max_length=255, verbose_name='驱动')),
                ('enable_ipv6', models.BooleanField(default=False, verbose_name='是否开启 IPv6')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'net_work_info',
            },
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='8ca211fc-b7e3-4e21-a8d8-cb5a341e6b5d', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CombinationContainer',
            fields=[
                ('container_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_info_id', models.UUIDField(editable=False, verbose_name='用户启动镜像组合ID')),
                ('combination_image_id', models.UUIDField(editable=False, verbose_name='漏洞组合镜像信息ID')),
                ('combination_image_info_id', models.UUIDField(editable=False, verbose_name='漏洞组合镜像信息ID')),
                ('user_id', models.IntegerField(verbose_name='使用用户ID')),
                ('docker_container_id', models.CharField(max_length=255, verbose_name='Docker容器运行进ID')),
                ('vul_host', models.CharField(max_length=255, verbose_name='容器漏洞URL')),
                ('container_status', models.CharField(max_length=255, verbose_name='容器状态')),
                ('container_port', models.CharField(max_length=255, verbose_name='容器端口')),
                ('container_flag', models.CharField(max_length=255, verbose_name='flag')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='容器创建时间，默认为当前时间')),
                ('is_check', models.BooleanField(default=False, verbose_name='Flag是否通过')),
                ('is_check_date', models.DateTimeField(null=True, verbose_name='Flag提交时间')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockerapi.ImageInfo', verbose_name='镜像ID')),
            ],
            options={
                'db_table': 'combination_container',
            },
        ),
    ]
