# Generated by Django 3.1.4 on 2021-05-28 23:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0005_auto_20201223_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTemp',
            fields=[
                ('temp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('time_range', models.IntegerField(verbose_name='计时模式时间')),
                ('image_name', models.TextField(default='', verbose_name='图片名称')),
                ('time_desc', models.TextField(null=True, verbose_name='计时模版描述')),
                ('flag_status', models.BooleanField(default=False, verbose_name='用于判断')),
            ],
            options={
                'db_table': 'time_Temp',
            },
        ),
        migrations.CreateModel(
            name='TimeRank',
            fields=[
                ('rank_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('user_name', models.CharField(max_length=256, verbose_name='用户名称')),
                ('rank', models.FloatField(verbose_name='Rank')),
                ('time_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockerapi.timetemp')),
            ],
            options={
                'db_table': 'time_rank',
            },
        ),
        migrations.CreateModel(
            name='TimeMoudel',
            fields=[
                ('time_id', models.CharField(default='e3080cd3-2ba6-4f67-85e7-18413c14deac', max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('start_time', models.FloatField(verbose_name='开始时间戳')),
                ('end_time', models.FloatField(verbose_name='结束时间')),
                ('status', models.BooleanField(default=False, verbose_name='用于判断')),
                ('temp_time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockerapi.timetemp')),
            ],
            options={
                'db_table': 'time_moudel',
            },
        ),
    ]
