# Generated by Django 3.1.4 on 2021-06-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0006_auto_20210604_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='a561f9cf-b0da-4fcc-8e15-700cb767e030', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
