# Generated by Django 3.1.4 on 2021-05-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0006_timemoudel_timerank_timetemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='bff901de-a681-4035-af21-5eddc51bf0db', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
