# Generated by Django 2.2.5 on 2019-12-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0006_auto_20191128_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationcontainer',
            name='vul_ip',
            field=models.CharField(default='', max_length=255, verbose_name='容器漏洞URL'),
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='bcedecaf-c63a-4898-a198-aaccd82fb977', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
