# Generated by Django 2.2.5 on 2019-12-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0008_auto_20191206_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinfo',
            name='net_work_client_id',
            field=models.CharField(default='', max_length=255, verbose_name='Dcoker网卡链接ID'),
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='09e1d7e1-9492-4222-82ff-5ed1b2ed0132', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
