# Generated by Django 2.2.5 on 2019-12-13 03:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0009_auto_20191206_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationinfo',
            name='master_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='入口节点ID'),
        ),
        migrations.AddField(
            model_name='combinationinfo',
            name='master_status',
            field=models.CharField(default='', max_length=255, verbose_name='入口节点状态'),
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='6cb6250c-d9f3-469e-a40c-56e667d2a508', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
