# Generated by Django 3.1.4 on 2021-06-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0009_auto_20210605_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='a49a302a-2631-48b2-a73b-b89741250827', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
