# Generated by Django 2.2.5 on 2019-12-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0010_auto_20191213_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationcontainer',
            name='vul_ip',
            field=models.CharField(max_length=255, verbose_name='容器漏洞URL'),
        ),
        migrations.AlterField(
            model_name='combinationinfo',
            name='master_id',
            field=models.UUIDField(editable=False, verbose_name='入口节点ID'),
        ),
        migrations.AlterField(
            model_name='combinationinfo',
            name='master_status',
            field=models.CharField(max_length=255, verbose_name='入口节点状态'),
        ),
        migrations.AlterField(
            model_name='containervul',
            name='time_model_id',
            field=models.CharField(max_length=255, verbose_name='时间模式 ID'),
        ),
        migrations.AlterField(
            model_name='networkinfo',
            name='net_work_client_id',
            field=models.CharField(max_length=255, verbose_name='Dcoker网卡链接ID'),
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='2b84a266-0d45-4c75-b184-5856eaf1ddd6', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
