# Generated by Django 3.1.4 on 2021-06-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0010_auto_20210605_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='1547c11c-5e5b-446c-84fa-d15cab047845', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
