# Generated by Django 3.1.4 on 2021-06-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0011_auto_20210605_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='9716f18e-22b2-462f-a850-b15ce822ec0c', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timetemp',
            name='rank_range',
            field=models.TextField(default='', verbose_name='漏洞类型'),
        ),
        migrations.AlterField(
            model_name='timetemp',
            name='time_img_type',
            field=models.TextField(default='', verbose_name='漏洞类型'),
        ),
    ]
