# Generated by Django 2.2.5 on 2019-12-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0011_auto_20191213_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationinfo',
            name='master_host',
            field=models.CharField(default='', max_length=255, verbose_name='入口节点Host'),
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='13c80d8b-a58c-4425-9a96-7a5fe68f8bef', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
