# Generated by Django 2.2.5 on 2019-12-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0012_auto_20191213_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationinfo',
            name='master_host',
            field=models.CharField(max_length=255, verbose_name='入口节点Host'),
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='196bfd80-0b46-4d6d-bee4-4fbb62f554c8', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
