# Generated by Django 3.1.4 on 2021-06-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0012_auto_20210605_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='808a3c18-3091-471d-9884-9b96056f1586', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
