# Generated by Django 2.2.5 on 2019-12-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0013_auto_20191213_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationimage',
            name='combination_desc',
            field=models.TextField(default='', null=True, verbose_name='环境描述'),
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='9a8928c8-b6fc-44a8-909b-f68522baa342', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
