# Generated by Django 3.1.4 on 2021-06-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0013_auto_20210605_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='1d2b72ed-cb22-4e6c-be27-4dc6433c66cb', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
