# Generated by Django 3.1.4 on 2021-06-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0014_auto_20210605_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetemp',
            name='image_ids',
            field=models.TextField(default='', verbose_name='镜像id'),
        ),
        migrations.AddField(
            model_name='timetemp',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='模版名称'),
        ),
        migrations.AlterField(
            model_name='timemoudel',
            name='time_id',
            field=models.CharField(default='dd31df9d-a263-4677-83a5-ad545680004e', max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timetemp',
            name='rank_range',
            field=models.TextField(default='', verbose_name='Rank范围'),
        ),
    ]
