# Generated by Django 2.2.5 on 2020-04-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0018_auto_20200110_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CombinationContainer',
        ),
        migrations.DeleteModel(
            name='CombinationImage',
        ),
        migrations.DeleteModel(
            name='CombinationImageInfo',
        ),
        migrations.DeleteModel(
            name='CombinationInfo',
        ),
        migrations.DeleteModel(
            name='NetWorkInfo',
        ),
        migrations.DeleteModel(
            name='TimeMoudel',
        ),
    ]
