# Generated by Django 2.2.5 on 2020-04-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0019_auto_20200428_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='containervul',
            name='vul_port',
            field=models.TextField(default='', verbose_name='容器对应端口'),
        ),
    ]
