# Generated by Django 2.2.5 on 2020-04-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0020_containervul_vul_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='is_ok',
            field=models.BooleanField(default=True, verbose_name='镜像是否可用'),
        ),
    ]
