# Generated by Django 2.2.5 on 2020-05-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0023_auto_20200506_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysconfig',
            name='config_name',
        ),
    ]
