# Generated by Django 2.2.10 on 2020-05-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='task_log',
            field=models.TextField(default='', verbose_name='任务执行日志'),
        ),
    ]
