# Generated by Django 2.2.5 on 2020-04-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='task_end_date',
            field=models.DateTimeField(null=True, verbose_name='任务结束时间'),
        ),
    ]
