# Generated by Django 2.2.5 on 2020-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200429_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='任务是否被查看'),
        ),
    ]
