# Generated by Django 2.2.10 on 2020-12-14 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('layout_image', '0002_auto_20201210_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='image_name',
            field=models.TextField(default='', verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='layout_id',
            field=models.UUIDField(default=uuid.UUID('653c0591-b530-4dda-ad2e-8cf9b4592522'), editable=False, primary_key=True, serialize=False, verbose_name='编排UUID'),
        ),
        migrations.AlterField(
            model_name='layoutdata',
            name='layout_user_id',
            field=models.UUIDField(default=uuid.UUID('667c2dd2-c30b-49d0-aa85-578e6a4e25cf'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layoutservice',
            name='service_id',
            field=models.UUIDField(default=uuid.UUID('8813b4e1-bce4-4083-9066-a1796693e161'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layoutservicecontainer',
            name='service_container_id',
            field=models.UUIDField(default=uuid.UUID('fb1f2003-47aa-4d24-ab95-e1290685e40e'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layoutservicenetwork',
            name='layout_service_network_id',
            field=models.UUIDField(default=uuid.UUID('968e1ca8-ba88-480d-be35-1df405831857'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
