# Generated by Django 2.2.10 on 2020-12-17 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('layout_image', '0004_auto_20201215_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutservicecontainer',
            name='is_check',
        ),
        migrations.RemoveField(
            model_name='layoutservicecontainer',
            name='is_check_date',
        ),
        migrations.AlterField(
            model_name='layout',
            name='layout_id',
            field=models.UUIDField(default=uuid.UUID('c191a745-0323-459f-9564-5044726118d5'), editable=False, primary_key=True, serialize=False, verbose_name='编排UUID'),
        ),
        migrations.AlterField(
            model_name='layoutdata',
            name='layout_user_id',
            field=models.UUIDField(default=uuid.UUID('e4c67565-5e78-4f21-b30b-23b640e08bde'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layoutservice',
            name='service_id',
            field=models.UUIDField(default=uuid.UUID('4f91a2f4-4da8-4c76-ae0a-9c6e9dd16885'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layoutservicecontainer',
            name='service_container_id',
            field=models.UUIDField(default=uuid.UUID('4e9cab49-b122-4511-bc60-659d353fcac1'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layoutservicenetwork',
            name='layout_service_network_id',
            field=models.UUIDField(default=uuid.UUID('2b266c98-5c97-48ef-9c8a-84e5e1cbab57'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
