# Generated by Django 2.2.10 on 2020-12-18 10:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapi', '0002_imageinfo_is_share'),
        ('layout_image', '0006_auto_20201217_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutservicecontainerscore',
            name='image_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dockerapi.ImageInfo', verbose_name='镜像ID'),
        ),
        migrations.AddField(
            model_name='layoutservicecontainerscore',
            name='service_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='layout_image.LayoutService', verbose_name='服务ID'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='layout_id',
            field=models.UUIDField(default=uuid.UUID('1e7da5fc-ef76-4850-aaa8-3b37b687b2bd'), editable=False, primary_key=True, serialize=False, verbose_name='编排UUID'),
        ),
        migrations.AlterField(
            model_name='layoutdata',
            name='layout_user_id',
            field=models.UUIDField(default=uuid.UUID('1299623c-5252-488a-b911-f7c4f21375d4'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layoutservice',
            name='service_id',
            field=models.UUIDField(default=uuid.UUID('0991d42a-3cbc-464e-ad23-56a72c9fe538'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layoutservicecontainer',
            name='service_container_id',
            field=models.UUIDField(default=uuid.UUID('16fb6d8e-018c-4c15-9471-fa021cbb4c38'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layoutservicecontainerscore',
            name='layout_service_container_score_id',
            field=models.UUIDField(default=uuid.UUID('86af7ff7-5740-44b1-b751-c699c9f3bf18'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layoutservicenetwork',
            name='layout_service_network_id',
            field=models.UUIDField(default=uuid.UUID('b20051b9-009a-4d39-b135-017fbae6c7fb'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
